### ISSUE TITLE
set the TitleView Width according to device width

### ISSUE THREAD

**Issue by Raviojha62** [AdityaDeshmane/iOSCustomPageControl#3]
Hi Aditya,
Its great code.
I am using this in my project, but one point i am facing problem.
I want to  divide the device width of the available views title , means if there are 3 views so it show equally size not set the text like Green as Greeeeeen  and Red as Reed .

**Comment by AdityaDeshmane** [comment]
Okay, i' ll add fix width option

**Comment by AdityaDeshmane** [comment]
Fixed added new propery

_pageControl.iCustomTabWidth =  [[UIScreen mainScreen] bounds].size.width/3;
