### ISSUE TITLE
About the button Constraints

### ISSUE THREAD

**Issue by SaumayRanjan** [AdityaDeshmane/iOSCustomPageControl#7]
Helllo Dude,
I am using your ADCustomPageControl code in my project. Please instruct me how can i set button (for page tittle) constraints. I take a scroll view with 64 from top. Please reply me as soon as possible.

**Comment by AdityaDeshmane** [comment]
Not getting you, please elaborate Or add screenshot explaining what you want to achieve

**Comment by SaumayRanjan** [comment]
It's done buddy, Now tell me that how to change selected page title text colour, which is on scroll view ?

**Comment by AdityaDeshmane** [comment]
-(void)setPageIndicatorToPageNumber:(int) pageNumber andShouldHighlightCurrentPage:(BOOL) bShouldHighlight

In above method at the end I am setting alpha of non selected button to 0.7 and selected to 1.0, you can set title font here

**Comment by SaumayRanjan** [comment]
Ohkkk Thanks bro.
